In [71]:
import numpy as np

In [93]:
k = ([-1,-1,-1],[-1,4,-1],[-1,-1,-1])
k=np.array(k)

In [94]:
print(k)

[[-1 -1 -1]
 [-1  4 -1]
 [-1 -1 -1]]


In [122]:
w=([1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8],
   [1,2,3,4,5,6,7,8])
w=np.array(w)

In [123]:
print(w)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [135]:
r=[]
count = 0
for i in range(len(w)-2):
  for j in range(len(w)-2):
    sub_matrix=(w[i:i+3,j:j+3])
    count += 1
    sum=0
    for x in range(len(k)):
      for y in range(len(k)):
        sum +=((sub_matrix[x][y]) * (k[x][y]))
    r.append(sum)
print(count)

36


In [136]:
r=np.array(r)

In [137]:
r.reshape(6,6)

array([[ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28]])

**Extend the program for any size of K provided K is a square one.**

In [168]:
n=int(input("Provide the size of  square matrix"))

Provide the size of  square matrix3


In [169]:
k_matrix =[]
for i in range (n):
  tmp = []
  for j in range (n):
    tmp.append(int(input("Enter the element")))
  k_matrix.append(tmp)
k_matrix=np.array(k_matrix)
print(k_matrix)

Enter the element-1
Enter the element-1
Enter the element-1
Enter the element-1
Enter the element4
Enter the element-1
Enter the element-1
Enter the element-1
Enter the element-1
[[-1 -1 -1]
 [-1  4 -1]
 [-1 -1 -1]]


In [170]:
r=[]
count = 0
for i in range(len(w)-(n-1)):
  for j in range(len(w)-(n-1)):
    sub_matrix=(w[i:i+n,j:j+n])
    count += 1
    sum=0
    for x in range(len(k_matrix)):
      for y in range(len(k_matrix)):
        sum +=((sub_matrix[x][y]) * (k_matrix[x][y]))
    r.append(sum)
print(count)

36


In [171]:
size=int(count/2)
for i in range (2,size):
  if (int(count/i) == i):
    m=i
    break
print(m)

6


In [172]:
r=np.array(r)
r.reshape(m,m)

array([[ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28],
       [ -8, -12, -16, -20, -24, -28]])